"""Initial enterprise schema

Revision ID: fa614f5efb4a
Revises: 
Create Date: 2026-02-18 14:49:29.962968

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'fa614f5efb4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('are_konsultation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('available_time', sa.DateTime(), nullable=True),
    sa.Column('kalenderwoche', sa.Integer(), nullable=False),
    sa.Column('saison', sa.String(), nullable=False),
    sa.Column('altersgruppe', sa.String(), nullable=False),
    sa.Column('bundesland', sa.String(), nullable=False),
    sa.Column('bundesland_id', sa.Integer(), nullable=True),
    sa.Column('konsultationsinzidenz', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_are_konsult_bundesland', 'are_konsultation', ['bundesland', 'kalenderwoche'], unique=False)
    op.create_index('idx_are_konsult_date_age', 'are_konsultation', ['datum', 'altersgruppe'], unique=False)
    op.create_index(op.f('ix_are_konsultation_available_time'), 'are_konsultation', ['available_time'], unique=False)
    op.create_index(op.f('ix_are_konsultation_datum'), 'are_konsultation', ['datum'], unique=False)
    op.create_index(op.f('ix_are_konsultation_id'), 'are_konsultation', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('virus_typ', sa.String(), nullable=False),
    sa.Column('target_source', sa.String(), nullable=False),
    sa.Column('target_key', sa.String(), nullable=True),
    sa.Column('target_label', sa.String(), nullable=True),
    sa.Column('strict_vintage_mode', sa.Boolean(), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=True),
    sa.Column('min_train_points', sa.Integer(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('baseline_metrics', sa.JSON(), nullable=True),
    sa.Column('improvement_vs_baselines', sa.JSON(), nullable=True),
    sa.Column('optimized_weights', sa.JSON(), nullable=True),
    sa.Column('proof_text', sa.String(), nullable=True),
    sa.Column('llm_insight', sa.String(), nullable=True),
    sa.Column('lead_lag', sa.JSON(), nullable=True),
    sa.Column('chart_points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backtest_mode_created', 'backtest_runs', ['mode', 'created_at'], unique=False)
    op.create_index('idx_backtest_target_created', 'backtest_runs', ['target_source', 'created_at'], unique=False)
    op.create_index(op.f('ix_backtest_runs_created_at'), 'backtest_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_backtest_runs_id'), 'backtest_runs', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_runs_mode'), 'backtest_runs', ['mode'], unique=False)
    op.create_index(op.f('ix_backtest_runs_run_id'), 'backtest_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_backtest_runs_status'), 'backtest_runs', ['status'], unique=False)
    op.create_index(op.f('ix_backtest_runs_target_source'), 'backtest_runs', ['target_source'], unique=False)
    op.create_index(op.f('ix_backtest_runs_virus_typ'), 'backtest_runs', ['virus_typ'], unique=False)
    op.create_table('brand_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('source_hash', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_brand_products_brand_active', 'brand_products', ['brand', 'active'], unique=False)
    op.create_index(op.f('ix_brand_products_active'), 'brand_products', ['active'], unique=False)
    op.create_index(op.f('ix_brand_products_brand'), 'brand_products', ['brand'], unique=False)
    op.create_index(op.f('ix_brand_products_id'), 'brand_products', ['id'], unique=False)
    op.create_index(op.f('ix_brand_products_last_seen_at'), 'brand_products', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_brand_products_product_name'), 'brand_products', ['product_name'], unique=False)
    op.create_index(op.f('ix_brand_products_updated_at'), 'brand_products', ['updated_at'], unique=False)
    op.create_index('uq_brand_products_brand_name', 'brand_products', ['brand', 'product_name'], unique=True)
    op.create_table('ganzimmun_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('available_time', sa.DateTime(), nullable=True),
    sa.Column('test_typ', sa.String(), nullable=False),
    sa.Column('anzahl_tests', sa.Integer(), nullable=True),
    sa.Column('positive_ergebnisse', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ganzimmun_data_available_time'), 'ganzimmun_data', ['available_time'], unique=False)
    op.create_index(op.f('ix_ganzimmun_data_datum'), 'ganzimmun_data', ['datum'], unique=False)
    op.create_index(op.f('ix_ganzimmun_data_id'), 'ganzimmun_data', ['id'], unique=False)
    op.create_table('google_trends_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('available_time', sa.DateTime(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('interest_score', sa.Integer(), nullable=True),
    sa.Column('is_partial', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trends_date_keyword', 'google_trends_data', ['datum', 'keyword'], unique=False)
    op.create_index(op.f('ix_google_trends_data_available_time'), 'google_trends_data', ['available_time'], unique=False)
    op.create_index(op.f('ix_google_trends_data_datum'), 'google_trends_data', ['datum'], unique=False)
    op.create_index(op.f('ix_google_trends_data_id'), 'google_trends_data', ['id'], unique=False)
    op.create_table('grippeweb_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('kalenderwoche', sa.Integer(), nullable=True),
    sa.Column('erkrankung_typ', sa.String(), nullable=False),
    sa.Column('altersgruppe', sa.String(), nullable=True),
    sa.Column('bundesland', sa.String(), nullable=True),
    sa.Column('inzidenz', sa.Float(), nullable=True),
    sa.Column('anzahl_meldungen', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_grippeweb_date_type', 'grippeweb_data', ['datum', 'erkrankung_typ'], unique=False)
    op.create_index(op.f('ix_grippeweb_data_datum'), 'grippeweb_data', ['datum'], unique=False)
    op.create_index(op.f('ix_grippeweb_data_id'), 'grippeweb_data', ['id'], unique=False)
    op.create_table('inventory_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('test_typ', sa.String(), nullable=False),
    sa.Column('aktueller_bestand', sa.Integer(), nullable=False),
    sa.Column('min_bestand', sa.Integer(), nullable=True),
    sa.Column('max_bestand', sa.Integer(), nullable=True),
    sa.Column('empfohlener_bestand', sa.Integer(), nullable=True),
    sa.Column('lieferzeit_tage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_levels_datum'), 'inventory_levels', ['datum'], unique=False)
    op.create_index(op.f('ix_inventory_levels_id'), 'inventory_levels', ['id'], unique=False)
    op.create_table('lab_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_global_default', sa.Boolean(), nullable=True),
    sa.Column('weight_bio', sa.Float(), nullable=True),
    sa.Column('weight_market', sa.Float(), nullable=True),
    sa.Column('weight_psycho', sa.Float(), nullable=True),
    sa.Column('weight_context', sa.Float(), nullable=True),
    sa.Column('last_calibration_date', sa.DateTime(), nullable=True),
    sa.Column('calibration_source', sa.String(), nullable=True),
    sa.Column('correlation_score', sa.Float(), nullable=True),
    sa.Column('analyzed_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_configurations_id'), 'lab_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_lab_configurations_is_global_default'), 'lab_configurations', ['is_global_default'], unique=False)
    op.create_table('marketing_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('opportunity_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('urgency_score', sa.Float(), nullable=False),
    sa.Column('region_target', sa.JSON(), nullable=True),
    sa.Column('trigger_source', sa.String(), nullable=True),
    sa.Column('trigger_event', sa.String(), nullable=True),
    sa.Column('trigger_details', sa.JSON(), nullable=True),
    sa.Column('trigger_detected_at', sa.DateTime(), nullable=True),
    sa.Column('target_audience', sa.JSON(), nullable=True),
    sa.Column('sales_pitch', sa.JSON(), nullable=True),
    sa.Column('suggested_products', sa.JSON(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('budget_shift_pct', sa.Float(), nullable=True),
    sa.Column('channel_mix', sa.JSON(), nullable=True),
    sa.Column('activation_start', sa.DateTime(), nullable=True),
    sa.Column('activation_end', sa.DateTime(), nullable=True),
    sa.Column('recommendation_reason', sa.String(), nullable=True),
    sa.Column('campaign_payload', sa.JSON(), nullable=True),
    sa.Column('playbook_key', sa.String(), nullable=True),
    sa.Column('strategy_mode', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id')
    )
    op.create_index('idx_opportunity_brand_status', 'marketing_opportunities', ['brand', 'status'], unique=False)
    op.create_index('idx_opportunity_playbook', 'marketing_opportunities', ['playbook_key'], unique=False)
    op.create_index('idx_opportunity_type_status', 'marketing_opportunities', ['opportunity_type', 'status'], unique=False)
    op.create_index('idx_opportunity_urgency', 'marketing_opportunities', ['urgency_score'], unique=False)
    op.create_index(op.f('ix_marketing_opportunities_brand'), 'marketing_opportunities', ['brand'], unique=False)
    op.create_index(op.f('ix_marketing_opportunities_created_at'), 'marketing_opportunities', ['created_at'], unique=False)
    op.create_index(op.f('ix_marketing_opportunities_id'), 'marketing_opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_marketing_opportunities_playbook_key'), 'marketing_opportunities', ['playbook_key'], unique=False)
    op.create_index(op.f('ix_marketing_opportunities_product'), 'marketing_opportunities', ['product'], unique=False)
    op.create_index(op.f('ix_marketing_opportunities_strategy_mode'), 'marketing_opportunities', ['strategy_mode'], unique=False)
    op.create_index(op.f('ix_marketing_opportunities_updated_at'), 'marketing_opportunities', ['updated_at'], unique=False)
    op.create_table('ml_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('forecast_date', sa.DateTime(), nullable=False),
    sa.Column('virus_typ', sa.String(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=True),
    sa.Column('upper_bound', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_forecast_date_virus', 'ml_forecasts', ['forecast_date', 'virus_typ'], unique=False)
    op.create_index(op.f('ix_ml_forecasts_created_at'), 'ml_forecasts', ['created_at'], unique=False)
    op.create_index(op.f('ix_ml_forecasts_forecast_date'), 'ml_forecasts', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_ml_forecasts_id'), 'ml_forecasts', ['id'], unique=False)
    op.create_table('notaufnahme_standorte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ik_number', sa.String(), nullable=False),
    sa.Column('ed_name', sa.String(), nullable=True),
    sa.Column('ed_type', sa.String(), nullable=True),
    sa.Column('level_of_care', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('state_id', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notaufnahme_state_type', 'notaufnahme_standorte', ['state', 'ed_type'], unique=False)
    op.create_index(op.f('ix_notaufnahme_standorte_id'), 'notaufnahme_standorte', ['id'], unique=False)
    op.create_index(op.f('ix_notaufnahme_standorte_ik_number'), 'notaufnahme_standorte', ['ik_number'], unique=True)
    op.create_table('notaufnahme_syndrome_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('ed_type', sa.String(), nullable=False),
    sa.Column('age_group', sa.String(), nullable=False),
    sa.Column('syndrome', sa.String(), nullable=False),
    sa.Column('relative_cases', sa.Float(), nullable=True),
    sa.Column('relative_cases_7day_ma', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('expected_lowerbound', sa.Float(), nullable=True),
    sa.Column('expected_upperbound', sa.Float(), nullable=True),
    sa.Column('ed_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notaufnahme_date_syndrome', 'notaufnahme_syndrome_data', ['datum', 'syndrome'], unique=False)
    op.create_index('idx_notaufnahme_filters', 'notaufnahme_syndrome_data', ['syndrome', 'ed_type', 'age_group'], unique=False)
    op.create_index(op.f('ix_notaufnahme_syndrome_data_datum'), 'notaufnahme_syndrome_data', ['datum'], unique=False)
    op.create_index(op.f('ix_notaufnahme_syndrome_data_id'), 'notaufnahme_syndrome_data', ['id'], unique=False)
    op.create_table('outbreak_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('virus_typ', sa.String(), nullable=False),
    sa.Column('final_risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('leading_indicator', sa.String(), nullable=True),
    sa.Column('confidence_level', sa.String(), nullable=True),
    sa.Column('confidence_numeric', sa.Float(), nullable=True),
    sa.Column('component_scores', sa.JSON(), nullable=True),
    sa.Column('data_source_mode', sa.String(), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outbreak_date_virus', 'outbreak_scores', ['datum', 'virus_typ'], unique=False)
    op.create_index(op.f('ix_outbreak_scores_datum'), 'outbreak_scores', ['datum'], unique=False)
    op.create_index(op.f('ix_outbreak_scores_id'), 'outbreak_scores', ['id'], unique=False)
    op.create_table('pollen_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('available_time', sa.DateTime(), nullable=True),
    sa.Column('region_code', sa.String(), nullable=False),
    sa.Column('pollen_type', sa.String(), nullable=False),
    sa.Column('pollen_index', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pollen_region_date', 'pollen_data', ['region_code', 'datum'], unique=False)
    op.create_index('idx_pollen_type_date', 'pollen_data', ['pollen_type', 'datum'], unique=False)
    op.create_index(op.f('ix_pollen_data_available_time'), 'pollen_data', ['available_time'], unique=False)
    op.create_index(op.f('ix_pollen_data_created_at'), 'pollen_data', ['created_at'], unique=False)
    op.create_index(op.f('ix_pollen_data_datum'), 'pollen_data', ['datum'], unique=False)
    op.create_index(op.f('ix_pollen_data_id'), 'pollen_data', ['id'], unique=False)
    op.create_index(op.f('ix_pollen_data_pollen_type'), 'pollen_data', ['pollen_type'], unique=False)
    op.create_index(op.f('ix_pollen_data_region_code'), 'pollen_data', ['region_code'], unique=False)
    op.create_index('uq_pollen_region_type_date', 'pollen_data', ['region_code', 'pollen_type', 'datum'], unique=True)
    op.create_table('product_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('applicable_types', sa.JSON(), nullable=True),
    sa.Column('applicable_conditions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_product_catalog_id'), 'product_catalog', ['id'], unique=False)
    op.create_table('school_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundesland', sa.String(), nullable=False),
    sa.Column('ferien_typ', sa.String(), nullable=False),
    sa.Column('start_datum', sa.DateTime(), nullable=False),
    sa.Column('end_datum', sa.DateTime(), nullable=False),
    sa.Column('jahr', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_holidays_dates', 'school_holidays', ['start_datum', 'end_datum'], unique=False)
    op.create_index(op.f('ix_school_holidays_id'), 'school_holidays', ['id'], unique=False)
    op.create_table('survstat_weekly_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_label', sa.String(), nullable=False),
    sa.Column('week_start', sa.DateTime(), nullable=False),
    sa.Column('available_time', sa.DateTime(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('bundesland', sa.String(), nullable=False),
    sa.Column('disease', sa.String(), nullable=False),
    sa.Column('incidence', sa.Float(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_survstat_disease_week', 'survstat_weekly_data', ['disease', 'week_start'], unique=False)
    op.create_index('idx_survstat_week_state', 'survstat_weekly_data', ['week_label', 'bundesland'], unique=False)
    op.create_index(op.f('ix_survstat_weekly_data_available_time'), 'survstat_weekly_data', ['available_time'], unique=False)
    op.create_index(op.f('ix_survstat_weekly_data_id'), 'survstat_weekly_data', ['id'], unique=False)
    op.create_index(op.f('ix_survstat_weekly_data_week_label'), 'survstat_weekly_data', ['week_label'], unique=False)
    op.create_index(op.f('ix_survstat_weekly_data_week_start'), 'survstat_weekly_data', ['week_start'], unique=False)
    op.create_index(op.f('ix_survstat_weekly_data_year'), 'survstat_weekly_data', ['year'], unique=False)
    op.create_index('uq_survstat_week_state_disease', 'survstat_weekly_data', ['week_label', 'bundesland', 'disease'], unique=True)
    op.create_table('upload_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('upload_type', sa.String(), nullable=False),
    sa.Column('file_format', sa.String(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('date_range_start', sa.DateTime(), nullable=True),
    sa.Column('date_range_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_history_created_at'), 'upload_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_upload_history_id'), 'upload_history', ['id'], unique=False)
    op.create_table('wastewater_aggregated',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('available_time', sa.DateTime(), nullable=True),
    sa.Column('virus_typ', sa.String(), nullable=False),
    sa.Column('n_standorte', sa.Integer(), nullable=True),
    sa.Column('anteil_bev', sa.Float(), nullable=True),
    sa.Column('viruslast', sa.Float(), nullable=True),
    sa.Column('viruslast_normalisiert', sa.Float(), nullable=True),
    sa.Column('vorhersage', sa.Float(), nullable=True),
    sa.Column('obere_schranke', sa.Float(), nullable=True),
    sa.Column('untere_schranke', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agg_date_virus', 'wastewater_aggregated', ['datum', 'virus_typ'], unique=False)
    op.create_index(op.f('ix_wastewater_aggregated_available_time'), 'wastewater_aggregated', ['available_time'], unique=False)
    op.create_index(op.f('ix_wastewater_aggregated_datum'), 'wastewater_aggregated', ['datum'], unique=False)
    op.create_index(op.f('ix_wastewater_aggregated_id'), 'wastewater_aggregated', ['id'], unique=False)
    op.create_table('wastewater_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standort', sa.String(), nullable=False),
    sa.Column('bundesland', sa.String(), nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('available_time', sa.DateTime(), nullable=True),
    sa.Column('virus_typ', sa.String(), nullable=False),
    sa.Column('viruslast', sa.Float(), nullable=True),
    sa.Column('viruslast_normalisiert', sa.Float(), nullable=True),
    sa.Column('vorhersage', sa.Float(), nullable=True),
    sa.Column('obere_schranke', sa.Float(), nullable=True),
    sa.Column('untere_schranke', sa.Float(), nullable=True),
    sa.Column('einwohner', sa.Integer(), nullable=True),
    sa.Column('unter_bg', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wastewater_date_virus', 'wastewater_data', ['datum', 'virus_typ'], unique=False)
    op.create_index('idx_wastewater_location', 'wastewater_data', ['standort', 'bundesland'], unique=False)
    op.create_index(op.f('ix_wastewater_data_available_time'), 'wastewater_data', ['available_time'], unique=False)
    op.create_index(op.f('ix_wastewater_data_datum'), 'wastewater_data', ['datum'], unique=False)
    op.create_index(op.f('ix_wastewater_data_id'), 'wastewater_data', ['id'], unique=False)
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('available_time', sa.DateTime(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('temperatur', sa.Float(), nullable=True),
    sa.Column('gefuehlte_temperatur', sa.Float(), nullable=True),
    sa.Column('luftfeuchtigkeit', sa.Float(), nullable=True),
    sa.Column('luftdruck', sa.Float(), nullable=True),
    sa.Column('wetter_beschreibung', sa.String(), nullable=True),
    sa.Column('wind_geschwindigkeit', sa.Float(), nullable=True),
    sa.Column('uv_index', sa.Float(), nullable=True),
    sa.Column('wolken', sa.Float(), nullable=True),
    sa.Column('niederschlag_wahrscheinlichkeit', sa.Float(), nullable=True),
    sa.Column('regen_mm', sa.Float(), nullable=True),
    sa.Column('schnee_mm', sa.Float(), nullable=True),
    sa.Column('taupunkt', sa.Float(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_weather_data_type', 'weather_data', ['data_type'], unique=False)
    op.create_index('idx_weather_date_city', 'weather_data', ['datum', 'city'], unique=False)
    op.create_index(op.f('ix_weather_data_available_time'), 'weather_data', ['available_time'], unique=False)
    op.create_index(op.f('ix_weather_data_datum'), 'weather_data', ['datum'], unique=False)
    op.create_index(op.f('ix_weather_data_id'), 'weather_data', ['id'], unique=False)
    op.create_table('backtest_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('real_qty', sa.Float(), nullable=True),
    sa.Column('predicted_qty', sa.Float(), nullable=True),
    sa.Column('baseline_persistence', sa.Float(), nullable=True),
    sa.Column('baseline_seasonal', sa.Float(), nullable=True),
    sa.Column('bio', sa.Float(), nullable=True),
    sa.Column('psycho', sa.Float(), nullable=True),
    sa.Column('context', sa.Float(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backtest_points_run_date', 'backtest_points', ['run_id', 'date'], unique=False)
    op.create_index(op.f('ix_backtest_points_created_at'), 'backtest_points', ['created_at'], unique=False)
    op.create_index(op.f('ix_backtest_points_date'), 'backtest_points', ['date'], unique=False)
    op.create_index(op.f('ix_backtest_points_id'), 'backtest_points', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_points_region'), 'backtest_points', ['region'], unique=False)
    op.create_index(op.f('ix_backtest_points_run_id'), 'backtest_points', ['run_id'], unique=False)
    op.create_table('llm_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('recommendation_text', sa.String(), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('suggested_action', sa.JSON(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('modified_action', sa.JSON(), nullable=True),
    sa.Column('forecast_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['ml_forecasts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_recommendations_created_at'), 'llm_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_recommendations_id'), 'llm_recommendations', ['id'], unique=False)
    op.create_table('product_condition_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('condition_key', sa.String(), nullable=False),
    sa.Column('rule_source', sa.String(), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=False),
    sa.Column('mapping_reason', sa.String(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['brand_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pcm_brand_approved', 'product_condition_mapping', ['brand', 'is_approved'], unique=False)
    op.create_index('idx_pcm_brand_condition', 'product_condition_mapping', ['brand', 'condition_key'], unique=False)
    op.create_index(op.f('ix_product_condition_mapping_brand'), 'product_condition_mapping', ['brand'], unique=False)
    op.create_index(op.f('ix_product_condition_mapping_condition_key'), 'product_condition_mapping', ['condition_key'], unique=False)
    op.create_index(op.f('ix_product_condition_mapping_id'), 'product_condition_mapping', ['id'], unique=False)
    op.create_index(op.f('ix_product_condition_mapping_is_approved'), 'product_condition_mapping', ['is_approved'], unique=False)
    op.create_index(op.f('ix_product_condition_mapping_product_id'), 'product_condition_mapping', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_condition_mapping_rule_source'), 'product_condition_mapping', ['rule_source'], unique=False)
    op.create_index(op.f('ix_product_condition_mapping_updated_at'), 'product_condition_mapping', ['updated_at'], unique=False)
    op.create_index('uq_pcm_product_condition', 'product_condition_mapping', ['product_id', 'condition_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_pcm_product_condition', table_name='product_condition_mapping')
    op.drop_index(op.f('ix_product_condition_mapping_updated_at'), table_name='product_condition_mapping')
    op.drop_index(op.f('ix_product_condition_mapping_rule_source'), table_name='product_condition_mapping')
    op.drop_index(op.f('ix_product_condition_mapping_product_id'), table_name='product_condition_mapping')
    op.drop_index(op.f('ix_product_condition_mapping_is_approved'), table_name='product_condition_mapping')
    op.drop_index(op.f('ix_product_condition_mapping_id'), table_name='product_condition_mapping')
    op.drop_index(op.f('ix_product_condition_mapping_condition_key'), table_name='product_condition_mapping')
    op.drop_index(op.f('ix_product_condition_mapping_brand'), table_name='product_condition_mapping')
    op.drop_index('idx_pcm_brand_condition', table_name='product_condition_mapping')
    op.drop_index('idx_pcm_brand_approved', table_name='product_condition_mapping')
    op.drop_table('product_condition_mapping')
    op.drop_index(op.f('ix_llm_recommendations_id'), table_name='llm_recommendations')
    op.drop_index(op.f('ix_llm_recommendations_created_at'), table_name='llm_recommendations')
    op.drop_table('llm_recommendations')
    op.drop_index(op.f('ix_backtest_points_run_id'), table_name='backtest_points')
    op.drop_index(op.f('ix_backtest_points_region'), table_name='backtest_points')
    op.drop_index(op.f('ix_backtest_points_id'), table_name='backtest_points')
    op.drop_index(op.f('ix_backtest_points_date'), table_name='backtest_points')
    op.drop_index(op.f('ix_backtest_points_created_at'), table_name='backtest_points')
    op.drop_index('idx_backtest_points_run_date', table_name='backtest_points')
    op.drop_table('backtest_points')
    op.drop_index(op.f('ix_weather_data_id'), table_name='weather_data')
    op.drop_index(op.f('ix_weather_data_datum'), table_name='weather_data')
    op.drop_index(op.f('ix_weather_data_available_time'), table_name='weather_data')
    op.drop_index('idx_weather_date_city', table_name='weather_data')
    op.drop_index('idx_weather_data_type', table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_wastewater_data_id'), table_name='wastewater_data')
    op.drop_index(op.f('ix_wastewater_data_datum'), table_name='wastewater_data')
    op.drop_index(op.f('ix_wastewater_data_available_time'), table_name='wastewater_data')
    op.drop_index('idx_wastewater_location', table_name='wastewater_data')
    op.drop_index('idx_wastewater_date_virus', table_name='wastewater_data')
    op.drop_table('wastewater_data')
    op.drop_index(op.f('ix_wastewater_aggregated_id'), table_name='wastewater_aggregated')
    op.drop_index(op.f('ix_wastewater_aggregated_datum'), table_name='wastewater_aggregated')
    op.drop_index(op.f('ix_wastewater_aggregated_available_time'), table_name='wastewater_aggregated')
    op.drop_index('idx_agg_date_virus', table_name='wastewater_aggregated')
    op.drop_table('wastewater_aggregated')
    op.drop_index(op.f('ix_upload_history_id'), table_name='upload_history')
    op.drop_index(op.f('ix_upload_history_created_at'), table_name='upload_history')
    op.drop_table('upload_history')
    op.drop_index('uq_survstat_week_state_disease', table_name='survstat_weekly_data')
    op.drop_index(op.f('ix_survstat_weekly_data_year'), table_name='survstat_weekly_data')
    op.drop_index(op.f('ix_survstat_weekly_data_week_start'), table_name='survstat_weekly_data')
    op.drop_index(op.f('ix_survstat_weekly_data_week_label'), table_name='survstat_weekly_data')
    op.drop_index(op.f('ix_survstat_weekly_data_id'), table_name='survstat_weekly_data')
    op.drop_index(op.f('ix_survstat_weekly_data_available_time'), table_name='survstat_weekly_data')
    op.drop_index('idx_survstat_week_state', table_name='survstat_weekly_data')
    op.drop_index('idx_survstat_disease_week', table_name='survstat_weekly_data')
    op.drop_table('survstat_weekly_data')
    op.drop_index(op.f('ix_school_holidays_id'), table_name='school_holidays')
    op.drop_index('idx_holidays_dates', table_name='school_holidays')
    op.drop_table('school_holidays')
    op.drop_index(op.f('ix_product_catalog_id'), table_name='product_catalog')
    op.drop_table('product_catalog')
    op.drop_index('uq_pollen_region_type_date', table_name='pollen_data')
    op.drop_index(op.f('ix_pollen_data_region_code'), table_name='pollen_data')
    op.drop_index(op.f('ix_pollen_data_pollen_type'), table_name='pollen_data')
    op.drop_index(op.f('ix_pollen_data_id'), table_name='pollen_data')
    op.drop_index(op.f('ix_pollen_data_datum'), table_name='pollen_data')
    op.drop_index(op.f('ix_pollen_data_created_at'), table_name='pollen_data')
    op.drop_index(op.f('ix_pollen_data_available_time'), table_name='pollen_data')
    op.drop_index('idx_pollen_type_date', table_name='pollen_data')
    op.drop_index('idx_pollen_region_date', table_name='pollen_data')
    op.drop_table('pollen_data')
    op.drop_index(op.f('ix_outbreak_scores_id'), table_name='outbreak_scores')
    op.drop_index(op.f('ix_outbreak_scores_datum'), table_name='outbreak_scores')
    op.drop_index('idx_outbreak_date_virus', table_name='outbreak_scores')
    op.drop_table('outbreak_scores')
    op.drop_index(op.f('ix_notaufnahme_syndrome_data_id'), table_name='notaufnahme_syndrome_data')
    op.drop_index(op.f('ix_notaufnahme_syndrome_data_datum'), table_name='notaufnahme_syndrome_data')
    op.drop_index('idx_notaufnahme_filters', table_name='notaufnahme_syndrome_data')
    op.drop_index('idx_notaufnahme_date_syndrome', table_name='notaufnahme_syndrome_data')
    op.drop_table('notaufnahme_syndrome_data')
    op.drop_index(op.f('ix_notaufnahme_standorte_ik_number'), table_name='notaufnahme_standorte')
    op.drop_index(op.f('ix_notaufnahme_standorte_id'), table_name='notaufnahme_standorte')
    op.drop_index('idx_notaufnahme_state_type', table_name='notaufnahme_standorte')
    op.drop_table('notaufnahme_standorte')
    op.drop_index(op.f('ix_ml_forecasts_id'), table_name='ml_forecasts')
    op.drop_index(op.f('ix_ml_forecasts_forecast_date'), table_name='ml_forecasts')
    op.drop_index(op.f('ix_ml_forecasts_created_at'), table_name='ml_forecasts')
    op.drop_index('idx_forecast_date_virus', table_name='ml_forecasts')
    op.drop_table('ml_forecasts')
    op.drop_index(op.f('ix_marketing_opportunities_updated_at'), table_name='marketing_opportunities')
    op.drop_index(op.f('ix_marketing_opportunities_strategy_mode'), table_name='marketing_opportunities')
    op.drop_index(op.f('ix_marketing_opportunities_product'), table_name='marketing_opportunities')
    op.drop_index(op.f('ix_marketing_opportunities_playbook_key'), table_name='marketing_opportunities')
    op.drop_index(op.f('ix_marketing_opportunities_id'), table_name='marketing_opportunities')
    op.drop_index(op.f('ix_marketing_opportunities_created_at'), table_name='marketing_opportunities')
    op.drop_index(op.f('ix_marketing_opportunities_brand'), table_name='marketing_opportunities')
    op.drop_index('idx_opportunity_urgency', table_name='marketing_opportunities')
    op.drop_index('idx_opportunity_type_status', table_name='marketing_opportunities')
    op.drop_index('idx_opportunity_playbook', table_name='marketing_opportunities')
    op.drop_index('idx_opportunity_brand_status', table_name='marketing_opportunities')
    op.drop_table('marketing_opportunities')
    op.drop_index(op.f('ix_lab_configurations_is_global_default'), table_name='lab_configurations')
    op.drop_index(op.f('ix_lab_configurations_id'), table_name='lab_configurations')
    op.drop_table('lab_configurations')
    op.drop_index(op.f('ix_inventory_levels_id'), table_name='inventory_levels')
    op.drop_index(op.f('ix_inventory_levels_datum'), table_name='inventory_levels')
    op.drop_table('inventory_levels')
    op.drop_index(op.f('ix_grippeweb_data_id'), table_name='grippeweb_data')
    op.drop_index(op.f('ix_grippeweb_data_datum'), table_name='grippeweb_data')
    op.drop_index('idx_grippeweb_date_type', table_name='grippeweb_data')
    op.drop_table('grippeweb_data')
    op.drop_index(op.f('ix_google_trends_data_id'), table_name='google_trends_data')
    op.drop_index(op.f('ix_google_trends_data_datum'), table_name='google_trends_data')
    op.drop_index(op.f('ix_google_trends_data_available_time'), table_name='google_trends_data')
    op.drop_index('idx_trends_date_keyword', table_name='google_trends_data')
    op.drop_table('google_trends_data')
    op.drop_index(op.f('ix_ganzimmun_data_id'), table_name='ganzimmun_data')
    op.drop_index(op.f('ix_ganzimmun_data_datum'), table_name='ganzimmun_data')
    op.drop_index(op.f('ix_ganzimmun_data_available_time'), table_name='ganzimmun_data')
    op.drop_table('ganzimmun_data')
    op.drop_index('uq_brand_products_brand_name', table_name='brand_products')
    op.drop_index(op.f('ix_brand_products_updated_at'), table_name='brand_products')
    op.drop_index(op.f('ix_brand_products_product_name'), table_name='brand_products')
    op.drop_index(op.f('ix_brand_products_last_seen_at'), table_name='brand_products')
    op.drop_index(op.f('ix_brand_products_id'), table_name='brand_products')
    op.drop_index(op.f('ix_brand_products_brand'), table_name='brand_products')
    op.drop_index(op.f('ix_brand_products_active'), table_name='brand_products')
    op.drop_index('idx_brand_products_brand_active', table_name='brand_products')
    op.drop_table('brand_products')
    op.drop_index(op.f('ix_backtest_runs_virus_typ'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_target_source'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_status'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_run_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_mode'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_created_at'), table_name='backtest_runs')
    op.drop_index('idx_backtest_target_created', table_name='backtest_runs')
    op.drop_index('idx_backtest_mode_created', table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_timestamp', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_are_konsultation_id'), table_name='are_konsultation')
    op.drop_index(op.f('ix_are_konsultation_datum'), table_name='are_konsultation')
    op.drop_index(op.f('ix_are_konsultation_available_time'), table_name='are_konsultation')
    op.drop_index('idx_are_konsult_date_age', table_name='are_konsultation')
    op.drop_index('idx_are_konsult_bundesland', table_name='are_konsultation')
    op.drop_table('are_konsultation')
    # ### end Alembic commands ###

