export interface OperationalRegionRow {
  code: string;
  name: string;
  rank: number | null;
  stage: string;
  eventProbability: number | null;
  trendLabel: string;
  trendPercent: number | null;
  budgetAmount: number | null;
  budgetShare: number | null;
  productCluster: string;
  keywordCluster: string;
  keywords: string[];
  channels: string[];
  signalStrength: number | null;
  businessGateLabel: string;
  businessGateHelper: string;
  evidenceLabel: string;
  evidenceHelper: string;
  actionLabel: string;
  summary: string;
  uncertainty: string;
  forecastConfidence: number | null;
  sourceFreshness: number | null;
  revisionRisk: number | null;
  crossSourceAgreement: number | null;
  decisionTrace: string[];
  allocationTrace: string[];
  recommendationTrace: string[];
}
